# Example:
apiVersion: backstage.io/v1alpha1
kind: Componente
metadata:
  name: S2 
  namespace: external-systems
  description: S2 
spec:
  type: service
  lifecycle: experimental
  owner: group:development-managers
  providesApis:
    - s2
    - internal/streetlights
    - drc-ecosistema
