apiVersion: backstage.io/v1alpha1
kind: Componente
metadata:
  name: DRC Tech 
  description: DRC Tech Ecosistema App
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: vladimir.abreu@drconsulta.com
  lifecycle: development
