apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: drc-tech-ecosistema-app
  description: Backstage controla a ordem na infraestrutura e permite as equipes de desenvolvimento enviem códigos de alta qualidade rapidamente, sem comprometer a autonomia.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: CNCF
  lifecycle: development
  system: drc-desenvolvedores
